### ISSUE TITLE
Update for pale moon 25.7 ?

### ISSUE THREAD

**Issue by Janaue** [Quicksaver/OmniSidebar#100]
Hello

I use your addon with my pale moon 25.7 portable on windows  but the last compatible version is  Version 1.3.2.1-signed . Can we have the latest version for this browser ?
for instance, the feature that we can click on an area the left to summon the left panel [as in AIOS]

For general knowledge, your addon is good since does not show the bug that AiOs shows with PM 25.7 : AiOS causes problems with the ''right-click, customize '' since if we try to customize twice, the menu bar is blanked out.

**Comment by Quicksaver** [comment]
Pale Moon is based on a version of Firefox code that is now very old, with an incredible amount of differences from the current version. Unfortunately I'm not able to maintain backwards compatibility like that, as it would require too much far too great an effort, and time which I don't have.
