### ISSUE TITLE
Nightly 44a1 2015-10-09 build. OmniSidebar v1.6-1.6.5 now scratching their browser.

### ISSUE THREAD

**Issue by zvitalikus** [Quicksaver/OmniSidebar#101]
Hello
Version 1.6-1.6.5 now scratching their browser.
OmniSidebar 1.5.4.1 working correctly.

In recent versions, you can not go to the page about:customizing
Also, there are errors in the browser interface. The panel OmniSidebar not displayed.

**Comment by Quicksaver** [comment]
The latest beta version fixes it: https://github.com/Quicksaver/OmniSidebar/releases/tag/v1.6.6b2

**Comment by zvitalikus** [comment]
Oh thank you. So fast)

**Comment by Quicksaver** [comment]
I had already fixed it, just haven't uploaded a final version to the Addons.Mozilla.Org homepage yet. :)
