### ISSUE TITLE
Add-ons sidebar always starts closed after restart

### ISSUE THREAD

**Issue by bibihh** [Quicksaver/OmniSidebar#103]
I have problem with Omnisidebar 1.6.6 and Firefox 42. I have that's problem with the last few previously versions of Firefox and Omnisidebar.

To reproduce the issue:

- Clean profile without any other add-onns;
- Default settings for Omnisidebar. The only think which I change is to use the twin sidebar, which is undocked and automatically hide when I am not using it.
- The problem is sometimes that twin bar is loosing focus after other addon installation, so is no more auto-unhiding when I move the cursor on the sidebar. The only thing which I can do is to left click on the twinbar so I can bring the focus again. The option "close/hide the sidebar when it loses focus" is active. I tried and when that option is disabled without any difference.

Sometimes I have other issue with the twinbar. When I am using it without any addons, the twinbar is breaking the menu button in firefox, so that button is not active until I close the firefox browser.

Hopefully you can reproduce the issue...

Regards

**Comment by Quicksaver** [comment]
I'm sorry, I don't fully understand what the issue is...

**Comment by bibihh** [comment]
I am not able to upload video on github so, please follow the link where I make video demonstration when the right panel is losing focus after any addon installation and restart of the Firefox. 

The pass for the file is: omni

http://www.filedropper.com/2015-10-2903-31-29-191

**Comment by Quicksaver** [comment]
Ah, I> understand, the sidebar starts closed after a restart. I'll give it a look.
