### ISSUE TITLE
Browser console doesn't work

### ISSUE THREAD

**Issue by REVerdi** [Quicksaver/OmniSidebar#106]
The browser console doesn't work for me. The buttons don't save the options I click.
When I open OmniSidebar already in the browser console, the following error occurs:

Handler function DebuggerClient.requester request callback threw an exception: Error: 'attach' request packet has no destination.
Stack: DebuggerClient.prototype.request@resource://gre/modules/devtools/dbg-client.jsm:736:1
DebuggerClient.prototype.attachTab@resource://gre/modules/devtools/dbg-client.jsm:496:5
TabTarget_makeRemote/attachTab@resource://gre/modules/commonjs/toolkit/loader.js -> resource:///modules/devtools/framework/target.js:426:7
TabTarget_makeRemote@resource://gre/modules/commonjs/toolkit/loader.js -> resource:///modules/devtools/framework/target.js:461:7
TF_forRemoteTab@resource://gre/modules/commonjs/toolkit/loader.js -> resource:///modules/devtools/framework/target.js:57:23
this.sidebarConsole.handleEvent/</<@resource://omnisidebar/defaultsContent.js?1447198079570 -> resource://omnisidebar/modules/utils/content.js -> resource://omnisidebar/modules/utils/Modules.jsm -> resource://omnisidebar/modules/compatibilityFix/console.jsm:36:8
DebuggerClient.requester/</<@resource://gre/modules/devtools/dbg-client.jsm:350:9
makeInfallible/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/devtools/DevToolsUtils.js:83:14
emitOnObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:112:9
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:89:38
Request.prototype.emit@resource://gre/modules/devtools/dbg-client.jsm:1224:29
DebuggerClient.prototype.onPacket/emitReply@resource://gre/modules/devtools/dbg-client.jsm:1035:29
DebuggerClient.prototype.onPacket@resource://gre/modules/devtools/dbg-client.jsm:1037:9
LocalDebuggerTransport.prototype.send/<@resource://gre/modules/devtools/dbg-client.jsm -> resource://gre/modules/devtools/transport/transport.js:569:11
makeInfallible/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/devtools/DevToolsUtils.js:83:14
makeInfallible/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/devtools/DevToolsUtils.js:83:14
Line: 736, column: 1

I believe that a picture says it all.

![omnisidebar browser console](https://cloud.githubusercontent.com/assets/618482/11080638/fcc48246-87fc-11e5-852f-d4a0fd471fd1.png)

**Comment by Quicksaver** [comment]
You're right, thanks for letting me know! I'm already working on it.

**Comment by REVerdi** [comment]
Thank you for the addon and the fix!
