### ISSUE TITLE
Re-sizing one sidebar while the other is closed resizes the closed sidebar

### ISSUE THREAD

**Issue by MOFTAD** [Quicksaver/OmniSidebar#107]
For example, if I resize the main sidebar while the twin sidebar is closed, upon opening the twin sidebar it is resized to a very narrow width. See here:

1. Initially: https://i.imgur.com/ri3xDVS.png
2. I resize one sidebar while the other is closed: https://i.imgur.com/fwRtXXj.png
3. Re-open the closed sidebar; it has been resized (see right side): https://i.imgur.com/uQ0klhr.png

- It doesn't matter if the open sidebar is widened or narrowed, nor which panels are set in the sidebars.
- The reset size is always the same (very narrow).
- No problems if re-sizing is done while both are open.
- The same thing occurs if I resize the twin sidebar while the main sidebar is closed (upon re-opening main sidebar, it is reset to the very narrow width).

**Comment by Quicksaver** [comment]
You're absolutely right. Thanks for letting me know! This will be fixed in the next update.
