### ISSUE TITLE
Web site opens in sidebar.

### ISSUE THREAD

**Issue by streetwolf** [Quicksaver/OmniSidebar#113]
Can't figure this one out.  When I go to https://www.thehealthplan.com/members/gold/meridian/index.cfm it opens in the sidebar.  I know it was working correctly at least a week ago.  I went back to the previous version of OSB but that didn't help.  Perhaps it is a patch on inbound that is causing it or maybe it's even on Nightly now.

**Comment by streetwolf** [comment]
I disabled OSB and the site still opened in the sidebar.  I entered the site in the location bar and that opened up where it belongs.  I then deleted the sidebar bookmark  and re-added it using the bookmark star on the context menu.  Now it opens up properly.

Weird, don't you think?

**Comment by Quicksaver** [comment]
If you open the properties of a bookmark, there's a box there to "Load this bookmark in the sidebar". Could you have checked it without noticing?

**Comment by streetwolf** [comment]
that seems to be the only explanation.  Right now the bookmark has that 
option no checked.

On 1/13/2016 11:34 AM, Luís Miguel wrote:
>
> If you open the properties of a bookmark, there's a box there to "Load 
> this bookmark in the sidebar". Could you have checked it without noticing?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Quicksaver/OmniSidebar/issues/113#issuecomment-171354064>.
>

-- 
Gary

**Comment by Quicksaver** [comment]
If that happens again check it out. OSB actually never checks it at all, or even uses it, that's all native Firefox code. But feel free to re-open if this happens again and OSB seems like the culprit.
