### ISSUE TITLE
the latest version of omni sidebar has two (bug) problems

### ISSUE THREAD

**Issue by re4ect** [Quicksaver/OmniSidebar#114]
One problem happens when unlocking the sidebar, when it's unlocked the menu below the "search all add-ons" search box has no background ( the "apply glass style" option does not look good with the FT Deepdark ff theme, everything looks grey and hard to read). 

![gcfgfc](https://cloud.githubusercontent.com/assets/14848245/12337621/07176c72-bad9-11e5-8a3d-78ec7712b24d.png)

The second problem is when the sidebar is docked the right side or the left side of the screen can be seen with a white background, this happens to me with the stylish theme mozilla.org inverted. 

![dcgfh](https://cloud.githubusercontent.com/assets/14848245/12338173/6dc9a75c-badc-11e5-92fa-26c073ca698f.png)

**Comment by Quicksaver** [comment]
> One problem happens when unlocking the sidebar, when it's unlocked the menu below the "search all add-ons" search box has no background

I'll take a look and try to fix that for the next version.

> One problem happens when unlocking the sidebar, when it's unlocked the menu below the "search all add-ons" search box has no background

That's impossible, that style affects only the webpage, not the sidebar. And the sidebar obviously doesn't affect the webpage. Ca you try disabling all your other add-ons and themes and see if that helps at all?

**Comment by re4ect** [comment]
I found out what the first problem is, it seems like this ff appearance [FT DeepDark] (https://addons.mozilla.org/en-US/firefox/addon/ft-deepdark/) ad-on is having a conflict with your add-on.

**Comment by Quicksaver** [comment]
I meant the issue about AMO webpage's background.
