### ISSUE TITLE
Tab Hover Bug

### ISSUE THREAD

**Issue by Vypre** [Quicksaver/OmniSidebar#115]
Great job on the last update in regards to the fixes for the FT DeepDark theme.The only glitch I've noticed is hovering over a tab (other than the one you have open) causes a strange flickering. This is with Tab Mix Plus installed as well. :)

**Comment by Quicksaver** [comment]
What kind of flickering? Can you try and capture this in a screencast please?

**Comment by Quicksaver** [comment]
Without more info, there's nothing I can do.
