### ISSUE TITLE
Slowdown/hang on loading huge history

### ISSUE THREAD

**Issue by Ulf3000** [Quicksaver/OmniSidebar#117]
Hi , my history is several years old and quite huge , when im trying to open the history sidebar, firefox goes to maxing out 2 cores for several minutes and hangs completely , seems to me its somehow instancing the history into its own memory or something. with a small addon "history sidebar button" theres no slowdown or any cpu spiking...

thanx for listening

**Comment by Quicksaver** [comment]
Does that happen if you open the history sidebar (Ctrl+H) with omnisidebar disabled?

**Comment by Ulf3000** [comment]
Hey this was quick :) ... yes its also happening with the shortcut, the only thing i can do is click the sidebar button and the moment it hides the sidebar the cpu and firefox is going back to normal

**Comment by Quicksaver** [comment]
I meant does it happen if you go to your add-ons manager and disable OmniSidebar?

**Comment by Ulf3000** [comment]
no everything is good with omni sidebar disabled , but if i install omnisidebar and that history-sidebar-button at the same time, and click the history button, the history loads up in omnisidebar correctly with no slowdown

**Comment by Quicksaver** [comment]
That's weird, they should both open the history sidebar in the same way. And it's definitely the same history sidebar that already exists in Firefox. I definitely need to look into this.

I wonder if it's dependent on how it's opened (it shouldn't be though but apparently that's the only explanation). Can you just run a couple of more tests for me please? Does the CPU lag if you open the history sidebar through the:
- keyboard shortcut Ctrl+H
- toolbar button included in OSB (not the one from that other add-on!)
- from the title menu in the sidebar, as in open the bookmarks sidebar, click its title and select the history sidebar.
- Firefox also has its history toolbar button that opens your history in a menu, and at the top of that menu there's a "View History Sidebar" entry, does that one also cause the lag?

**Comment by Ulf3000** [comment]
hey sorry , you can unfile this bug .. it seems to be the ORIGINAL firefox sidebar which is hanging .

i made a fresh profile , copied over only the places.sqlite , restarted the profile  and bam same problem with just ctrl+h the moment i decide to unfold the "older than 6 months" history tree  . strangly enough the sdk way of loading the sidebar(that small other addon ) doesn´t hang even a little bit. yeah , firefox´s code is a complete mess right now , hopefully things ll settle down when theyve finally made their switch ...

**Comment by Quicksaver** [comment]
I'll still take a look at that other add-on, it's strange that it works just fine, but maybe I can figure out why that is happening and use it to fix it in OSB at least.

**Comment by Ulf3000** [comment]
hey then im glad you´re taking this on ! :) 

i can´t really recreate this but ive had omnisidebar installed for maybe around 9 months or so and never had this problem before , so i guess its one of the last updates to firefox which caused this ..

**Comment by Ulf3000** [comment]
loading chrome://browser/content/history/history-panel.xul in a tab is also working correctly with no slowdown ... its firefox 44, im gonna try it on nightly now

**Comment by Quicksaver** [comment]
The button from "history Sidebar Button" really doesn't do anything special, it just loads the uri into the sidebar like every other menu or button in OSB.

Please let me know if anything comes out from your investigation, it really does seem like an issue with Firefox itself not handling a large history volume like that for some reason. But if you again find reason to believe it's caused by OSB feel free to reopen this.
