### ISSUE TITLE
Compatibilty with addon Clean Uninstall

### ISSUE THREAD

**Issue by MacgyverJohnson** [Quicksaver/OmniSidebar#120]
Can u make this addon compatibile with Clean uninstall [Can u make this addon compatibile with ](url) which is a nifty addon for cleaning out ur prefs.js file. This addon works fine from about:addons page but not from OSB

**Comment by Quicksaver** [comment]
I assume you mean [Clean Uninstall](https://addons.mozilla.org/firefox/addon/clean-uninstall/). If yes, what's the problem exactly?

**Comment by MacgyverJohnson** [comment]
addons that can open windows {with tiltle bar and close option} seem to work fine [actually all addons to this day has worked fine i.e when launched the preference option from omni sidebar . But this paticular addon does not open its preference in a window or dialog box  which have titlebar or close button but on what maybe called overlay. At any rate i have informed the dev about this and i think its Clean uninstall addons's problem not omni sidebar's..but still wanted to let u know......it could be that addons that open its preference windows as overlay might not work with omni sidebar..imho
Below attached gif showing all other addons working but Clean uninstall isnt working...If u think its not omni sidebars prob then just ignore by long post :)
![clean uninstall](https://cloud.githubusercontent.com/assets/17729946/14570169/aa622c68-0364-11e6-98c3-a5b5fb6dcb97.gif)

**Comment by Quicksaver** [comment]
Ah, I understand. It actually might not be possible to open it in the sidebar. That overlay is completely constructed by Clean Uninstaller (I assume, because I had never seen it before, and I'm almost positive it's not Firefox itself doing it). And the sidebar is much narrower by nature than the add-on's manager in a tab, it simply may not fit at all.

But of course, I'll take a look when I can.

**Comment by MacgyverJohnson** [comment]
Amazing response time!! Dev you don't let people down. Counting on u :100:

**Comment by Quicksaver** [comment]
It is as I suspected. Unfortunately I can't fix this from my side, Clean Uninstall is specifically initializing itself in tabs only, and I can't access its initialization routines from the outside (i.e. from OmniSidebar). :(

**Comment by Quicksaver** [comment]
The latest Clean Uninstall update seems to work great, please let either me or its developer know if you still have any problems.
