### ISSUE TITLE
Slight misbehavior with Classic Theme Restorer's "Add-on list: compact view" option enabled

### ISSUE THREAD

**Issue by HYBRID-BEING** [Quicksaver/OmniSidebar#121]
Add-on list becomes several pixels wider than it's frame, even when there is enough space. Same with "Alternative appearance" regardless of "Add-on list: compact view" option.
![pic](https://cloud.githubusercontent.com/assets/1691231/14597564/f71900fa-0566-11e6-8773-df4d083a8ae2.png)

**Comment by Aris-t2** [comment]
I will fix this on CTR 1.5.3beta1+. ;-)

**Comment by Quicksaver** [comment]
The latest CTR beta looks great! @Aris-t2 thanks so much for taking a look so quickly. @HYBRID-BEING if you still have any problems, please let either me or Aris know. The latest [CTR beta is here](https://addons.mozilla.org/firefox/addon/classicthemerestorer/versions/) by the way.
