### ISSUE TITLE
addons tab categories buttons glitch

### ISSUE THREAD

**Issue by nonat** [Quicksaver/OmniSidebar#122]
Hey, I found when ive got both Stylish & Custom Buttons installed, the latter category button gets repositioned to a second row of its own

1) first reprodiced this on a new profile, installed OmniSidebar Stylish & Custom Buttons in that order (relevant)
2) at first thought it was a custom buttons incompatibility , but then uninstalled Stylish & after restarting, the Custom Buttons category button was sitting on the top row
3)  So then reinstalled Stylish which retook its old position, but the Custom Buttons wasnt repositoned back on the second row, remained with the others on the first !? 

So seems whatever the problem, one solution could be for the three addons play nice, just need to install Custom Buttons before Stylish - havent retested it tho

Either way, wrote a workaround to hide the second row (if present) till hovered, then to float it. Your welcome to use it if it looks good: & the only discernable difference if theres only one row of category buttons is a 0,0,0,.1 background when hovering on them with glass style, only needed cause the second row floats over the list-view without a background, so needs something to indicate whatevers there are category buttons, tho doesnt extend below the list-view top border with only one row

@namespace url(http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul);
@-moz-document url(about:addons) {

#addons-page.inSidebar #nav-header {
margin-bottom: 40px }

#addons-page.inSidebar #categories {
position: fixed ; z-index: 1 ; left: 0 ; top: 39px }

#addons-page.inSidebar.glassStyle #categories {
top: 50px ; margin-left: -4px }  /* margin related to scrollbox background */ 

#addons-page.inSidebar #categories richlistitem {
height: 38px } /* limited value, lines up bottom margin only on Stylish tab */ 

#addons-page.inSidebar #categories > scrollbox:not(:hover) {
height: 40px }

#addons-page.inSidebar.glassStyle #categories > scrollbox:hover {
border-radius: 0 5px 0 0 ; background: rgba(0,0,0,.1) }
}

**Comment by Quicksaver** [comment]
Please try disabling that style and create a new one as in the commit, to confirm that it fixes it.

```CSS
@namespace url(http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul);
@-moz-document url("about:addons") {
	.inSidebar #categories #stylishStrings {
		display: none;
	}
}
```

**Comment by nonat** [comment]
wow, yes confirm that does fixe it. 

Custom Buttons gets repositioned to the first row with just that code. Thanks for that

**Comment by Quicksaver** [comment]
No problem, I'm glad to hear it. :)
