### ISSUE TITLE
Firefox 48- several issues

### ISSUE THREAD

**Issue by MikeVirtual** [Quicksaver/OmniSidebar#127]
Downloads, Addons, etc. don't open in sidebar
Options Apply and OK don't do anything so you can't change options

**Comment by Quicksaver** [comment]
There are no "Apply" and "Ok" buttons in the options tab, so I don't know what you mean by that. As for panels not opening in the sidebar, does that also happen if you disable all your other add-ons except for OSB?

**Comment by MikeVirtual** [comment]
Apologies, posted on wrong thread - was All-in-one Sidebar that is no longer working.
