### ISSUE TITLE
Add-ons tab not opening in Omnisidebar anymore

### ISSUE THREAD

**Issue by zetapulse** [Quicksaver/OmniSidebar#129]
It still works if I open it via the drop-down menu at the top, but using the keyboard shortcut or any external command opens it in a regular tab. I disabled/enabled the option for the add-ons tab to open in Omnisidebar in Omnisidebar's options, just to make sure.

The only recent changes made to my Firefox that might have caused this are the following:
- Firefox updated to 48
- Installed add-on Keybinder (tried disabling it as well as just the shortcut for add-ons)

It's selfish of me to say this only when I'm having an issue with it, but thank you for this great add-on, & all your work!

**Comment by Quicksaver** [comment]
I already noticed this but haven't had time to fix it yet. I'll be sure to try and fix it soon.

**Comment by zetapulse** [comment]
Good to know that it's a common issue & it's not just my Omnisidebar that's broken.
You're alright mate. Have a good one.

**Comment by Aliaspub** [comment]
Like you, Omnisidebar no more works on my Firefox since stable update 48.0.
I love this add-on, so I hope a fix will be coming soon...!
Keep it up ;)

**Comment by Quicksaver** [comment]
> Like you, Omnisidebar no more works on my Firefox since stable update 48.0.

It's only the keyboard shortcuts for specific sidebars, everything else should still work. ;)

**Comment by Aliaspub** [comment]
Maybe it would but it does not. Uninstall and reinstall Omnisidebar is 
not sufficient. I have had to install the add-on eCleaner to delete all 
tracks let by your add-on, to reinstall it properly then. Now it works.

Thank you

**Comment by nonentity1001** [comment]
Ditto

**Comment by zetapulse** [comment]
> I have had to install the add-on eCleaner to delete all tracks let by your add-on, to reinstall it properly then. Now it works.
Is that including the add-ons tab opening in Omnisidebar when you press Ctrl+Shift+A (and you set it to open in the sidebar by default)?

**Comment by Aliaspub** [comment]
I don't know now the problem is fixed for me... Thread closed according to me...

**Comment by MacgyverJohnson** [comment]
I don't think @Aliaspub's problem  was ctrl+shift+a to begin with........tested with firefox fresh profile..problem(ctrl+shift+a or any custom keyboard shortcut to open addons manager doesnt open it in sidebar)....good to know its not just me

**Comment by MacgyverJohnson** [comment]
When came we expect this bug to be fixed @Quicksaver 
Just for this bug I am using Firefox previous version
Thanks in advance!!!

**Comment by Quicksaver** [comment]
I honestly don't have a precise answer... I *should* be able to get to it before Firefox 50.

**Comment by Quicksaver** [comment]
I'm sorry it took me so long to get to it. This should be fixed in [beta version 1.6.14b1](https://github.com/Quicksaver/OmniSidebar/releases/tag/v1.6.14b1). Please give it a try and let me know how it works for you.

**Comment by Glubzor** [comment]
Works in FF 51.0b4 32 bits

**Comment by zetapulse** [comment]
It bloody works! What a pleasant surprise. It feels to get your PC working closer to how you want it to. Many thanks to you!
FF 50.1.0
