### ISSUE TITLE
Enhancement: Allow remote sites in the sidebar

### ISSUE THREAD

**Issue by Gitoffthelawn** [Quicksaver/OmniSidebar#132]
I seem to remember an extension that would allow any website in the sidebar.

Could the "Go" functionality in OmniSidebar be extended to include this functionality, or would it cause issues?

**Comment by Quicksaver** [comment]
Same as #40.

**Comment by Gitoffthelawn** [comment]
Thanks.  I didn't read that far back.  I will now!  Thanks again.
