### ISSUE TITLE
Automatically hide to the side function?

### ISSUE THREAD

**Issue by SLK350** [Quicksaver/OmniSidebar#133]
Does not work properly for me using latest Firefox 64bit nightly & Omnisidebar 1.6.13.

When I drag&drop a bookmark to the sidebar it get stuck on screen and I have to restart Firefox to get it working (autohiding) again. I have tried disabling all my other addons but does not help.

**Comment by Quicksaver** [comment]
I'll take a look into it. Thanks for letting me know.

**Comment by SLK350** [comment]
Nevermind it seems to be working fine. I'm sometimes running remote desktop to home computer. When doing this a tiny frame can be seen around firefox window which causes things to be messed up.

**Comment by Quicksaver** [comment]
Ok then.
