### ISSUE TITLE
Omnisidebar closes when it shold just be hidden

### ISSUE THREAD

**Issue by zetapulse** [Quicksaver/OmniSidebar#135]
Currently, if you have clicked on Omnisidebar (or otherwise set the focus on it) & use a close-tab shortcut (Ctrl+W by default), the sidebar closes & will not be opened (or will not show if hidden) again unless you access one of the sidebar windows (opening Downloads, Bookmarks or History). I'd like to suggest an enhancement/feature that prevents this from happening.
I'm no programmer, but I'm under the impression that Omnisidebar works like a tab, in which case setting it to a protected tab would do the trick.

**Comment by Quicksaver** [comment]
The sidebar is not a tab, so there is no protected status like that for it. And that shortcut should not be closing it at all, I just tried it and it's working as expected. Does that happen if you disable all your other add-ons except for OSB? What operating system are you on?

**Comment by zetapulse** [comment]
OS: Windows 7 Ultimate SP1 x64
After disabling all add-ons, it worked as you said, & after re-enabling them one-by-one, well... it still works like you said.
I noticed though that I still can close the sidebar (won't pop up on mouse over) by using the shortcut for whatever window is currently open in it, e.g., if sidebar is showing Downloads & you press Ctrl+J it will "close". This applies for History & Bookmarks as well, & applies with no other add-ons enabled.

**Comment by Quicksaver** [comment]
That's working as expected. Remember "hiding" and "closing" the sidebar are different things. Keyboard shortcuts and most other ways where you open the sidebar will also let you close it, it's always been like that even without OSB.

**Comment by Quicksaver** [comment]
I forgot to mention, it's weird that it started working just like that. Please let me know if it starts losing again with the close tab keyboard shortcut.
