### ISSUE TITLE
Show hidden Omnisidebar when opening Downloads/Bookmarks/History/Addons

### ISSUE THREAD

**Issue by zetapulse** [Quicksaver/OmniSidebar#136]
Currently, when OSB is hidden & you try to access Downloads/Bookmarks/History/Addons (using shortcuts Ctrl+J/B/H/Shift+A), the sidebar's contents change suitably (except Addons due to https://github.com/Quicksaver/OmniSidebar/issues/129 ), but it won't come out of hiding, prompting the necessity of moving the mouse over to the side to get it to show. I'd like to suggest an enhancement to make it show when something that opens in it is activated.
FYI, I don't know if this may be related, but currently, when clicking on an item in the drop-down list, if I don't move the mouse immediately after over the sidebar it will hide, I suppose thinking the mouse was hovering over the list & therefore not focused on the sidebar.

**Comment by Quicksaver** [comment]
Both of those should already be happening. I'm beginning to think you definitely have something interfering with the normal sidebar behavior. Please try what I suggested in your other issue, and let me know of your system as well.

**Comment by zetapulse** [comment]
As per https://github.com/Quicksaver/OmniSidebar/issues/135#issuecomment-247626431 , I tried with every add-on disabled & OSB acted accordingly (except downloads would close if you don't quickly hover over it. Nitpicking). Trying to isolate the problematic add-on, I came across something unexpected: add-ons that require a restart to enable/disable them would randomly cause my issue. Once one of them triggers the issue, it cannot be restored to working order before disabling all add-ons.
The first time I enabled All Tabs Helper, Back to Close & Bazzacuda Image Saver, OSB it kept working as advertized, but when I enabled Download Manager Tweak my issues started. Disabling them one-by-one did not restore the matter until every add-on (even the ones that don't need restarts, aside from OSB) were disabled. I tried again & this time All Tabs Helper caused the issue.
A small thing I noticed is that when the issue was temporarily solved, in the History or Bookmarks OSB, the text cursor would be in the OSB search box, but when the issue is reproduced, activating History or Bookmarks doesn't set focus on said search box.

**Comment by Quicksaver** [comment]
> A small thing I noticed is that when the issue was temporarily solved, in the History or Bookmarks OSB, the text cursor would be in the OSB search box, but when the issue is reproduced, activating History or Bookmarks doesn't set focus on said search box.

When you open these sidebars, the cursor should always go to this textbox. This is the default behavior in Firefox even and OSB doesn't change that at all. While the cursor is there, the sidebar has focus of course so it will always be visible as long as the cursor is there.

Note that for sidebars where there is no textbox to focus (or even for those that do but don't get focus for some reason), opening a sidebar should at least show it for about a second (don't remember exactly how long off my head), and it should automatically hide by itself unless you move the pointer over it. I'm guessing this is not happening either then?

**Comment by zetapulse** [comment]
Correct, it's not happening with windows that don't have a textbox either.

**Comment by Quicksaver** [comment]
This should be fixed in [beta version 1.6.14b1](https://github.com/Quicksaver/OmniSidebar/releases/tag/v1.6.14b1). Please give it a try and let me know how it works for you.

**Comment by mikeparadinas** [comment]
YES ITS FIXED!!!!!!!!! using Firefox Nightly 53.0a1

**Comment by zetapulse** [comment]
It's working & the sidebar textbox is taking focus when I open History or Bookmarks now 👍 
FF 50.1.0
