### ISSUE TITLE
Switching between sidebars is broken on Nightly (51.0a1)

### ISSUE THREAD

**Issue by the-nothingman** [Quicksaver/OmniSidebar#137]
Same as title when sidebar is installed on current Nightly there is no ability to switch between sidebar views either using the drop down menu or right-click on the sidebar switch (oddly enough buttons still work) Trying using either option will just show them as blank without any option to switch to. 

![2016-09-17 1](https://cloud.githubusercontent.com/assets/7260835/18611813/f492a518-7d14-11e6-88a8-2d888a24b3c9.jpg)

**Comment by Lurtzae** [comment]
Can confirm this for Aurora 51.0a2.

**Comment by zephyrer** [comment]
This is because the window.SocialSidebar has been removed from latest Firefox. After simply disabled all about this object, it's ok.
I commented all locations about SocialSidebar/Social in menus.jsm, and commented "Modules.load('social');" and "Modules.unload('social');" in omnisidebar.jsm, and modified isSocial() functions to always return false.
Of course, must disable Firefox extension signing first.
Good Luck!

**Comment by Sporif** [comment]
> I commented all locations about SocialSidebar/Social in menus.jsm, and commented "Modules.load('social');" and "Modules.unload('social');" in omnisidebar.jsm, and modified isSocial() functions to always return false

@zephyrer Thanks for that, worked great. Yes I made this account just to thank you :)

**Comment by Quicksaver** [comment]
This should be fixed in [beta version 1.6.14b1](https://github.com/Quicksaver/OmniSidebar/releases/tag/v1.6.14b1). Please give it a try and let me know how it works for you.

**Comment by Lurtzae** [comment]
Works like a charm, thanks a lot.

**Comment by Sporif** [comment]
Yes it fixed it, thanks. On a separate note, are the Toolbar buttons supposed to be closer together and have a outline upon hover?

**Comment by mikeparadinas** [comment]
screenshot what you mean fam

**Comment by Quicksaver** [comment]
@Sporif yes, it's supposed to more closely resemble the button style of Firefox's main toolbar. (The previous style was also the default in Firefox at one point, but has since been removed.)
