### ISSUE TITLE
Discovery Panel in OSB

### ISSUE THREAD

**Issue by EMLVIRUS** [Quicksaver/OmniSidebar#140]
See the screen shot below
![1](https://cloud.githubusercontent.com/assets/16912240/19672012/b586d76e-9aa5-11e6-9178-28aa8ba94499.png)

**Comment by EMLVIRUS** [comment]
I just forgot a hint: the buttons in OSB in inaccessible and unclickable as the mouse became a block sign.

**Comment by Quicksaver** [comment]
This should also be fixed in [beta version 1.6.14b1](https://github.com/Quicksaver/OmniSidebar/releases/tag/v1.6.14b1). Please give it a try and let me know how it works for you.

**Comment by EMLVIRUS** [comment]
Perfectly fixed, thanks.
