### ISSUE TITLE
OmniSidebar & Nightly 53

### ISSUE THREAD

**Issue by harl** [Quicksaver/OmniSidebar#141]
I'd just like to inform you that the drop-down menu isn't working properly with the latest Nightly versions.
The list it's supposed to show is essentially just empty and the whole menu's height is only 5px.
![omnisidebar_nightly53_dropdown_01](https://cloud.githubusercontent.com/assets/1159811/20866969/0570f06c-ba3a-11e6-8540-1ba2faf55fb2.png)

**Comment by Quicksaver** [comment]
Already fixed in the next update (already uploaded to AMO, should auto-update soon). In the meantime, you can try [beta version 1.6.14b1](https://github.com/Quicksaver/OmniSidebar/releases/tag/v1.6.14b1) if you don't want to wait for it.
