### ISSUE TITLE
Incompatibility with Download Statusbar

### ISSUE THREAD

**Issue by Xinok** [Quicksaver/OmniSidebar#55]
There's an incompatibility between OmniSidebar and [Download Statusbar](https://addons.mozilla.org/en-US/firefox/addon/download-status-bar/). Sometimes, when closing and restarting Firefox, the toolbar buttons in the sidebar toolbar will disappear (meaning I have to enter Customize and place them on the toolbar again).

I was able to reproduce this issue in a clean install of Firefox. Simply install both addons, place some buttons in the sidebar toolbar, and restart Firefox a few times. The buttons should disappear.

Firefox 29.0.1
Windows 7 64-bit
OmniSidebar 1.47
[Download Statusbar 10.0.0](https://addons.mozilla.org/en-US/firefox/addon/download-status-bar/)

**Comment by Quicksaver** [comment]
Firefox 35 has been released already, so this bug shouldn't happen anymore with it. Please re-open (or open a new issue) if it happens again.
