### ISSUE TITLE
Undocked sidebar problem

### ISSUE THREAD

**Issue by streetwolf** [Quicksaver/OmniSidebar#67]
Nightly builds have turned on the pref to allow D2D 1.1.  You can verify if this applies to you in about:support.

I've been using this bit of css code to hide the sidebar scroll bar:

   #bookmarksPanel scrollbar, #history-panel scrollbar {
    display: none !important;
  }

Now the undocked sidebar only shows the icons unless you hover over one of them in which case the description will appear temporarily. Removing this css code and showing the scroll bar 'fixes' the problem.  A docked sidebar doesn't have this problem when I don't display the scroll bar.

Seems to be a few problems, which I have reported, when it comes to an undocked sidebar.

**Comment by Quicksaver** [comment]
So unless I missed something, all the issues we discussed here should have been fixed for a while now. Let me know if you run into any others.
