### ISSUE TITLE
Bug with margins when sidebar is undocked

### ISSUE THREAD

**Issue by RogerUP13** [Quicksaver/OmniSidebar#70]
If hide header when sidebar is undocked (uncheck all checkboxes in appearance group in settings)
![settings](https://cloud.githubusercontent.com/assets/7015211/5549146/070aa070-8b94-11e4-8e69-1238c246f876.PNG)
appear error margins: top large,  bottom is missing
![bug](https://cloud.githubusercontent.com/assets/7015211/5549147/070b26f8-8b94-11e4-9712-a12cafb65cc7.PNG)
If panel header is visible, (check one checkbox in group) all displays correct
![correct](https://cloud.githubusercontent.com/assets/7015211/5549148/070fbccc-8b94-11e4-87fb-2e92fcd927ef.PNG)
I use OmniSidebar Version 1.5 from December 13, 2014

**Comment by Quicksaver** [comment]
I'm sorry about the big delay on this. Could you please give beta version 1.5.1b1 a try and let me know if that fixes the issue for you? You can find it at the top of https://addons.mozilla.org/firefox/addon/omnisidebar/versions/.

**Comment by RogerUP13** [comment]
Thank you for bug fix. In new beta version this bug is not reproduced.

**Comment by Quicksaver** [comment]
Great, thanks for letting me know.
