### ISSUE TITLE
MileWideBack/EdgeWise scroll functions not working

### ISSUE THREAD

**Issue by spideymouse** [Quicksaver/OmniSidebar#75]
Hi Luis! Great job on getting the autoshow delay working with MileWideBack and EdgeWise!

The last big problem I'm finding with using OSB with either of these addons is that OSB seems to break their mousewheel scroll functions. Is there a way to fix this? Might be a conflict with the OnMouseOver functionality. I'll definitely be using OSB full-time if this gets fixed!

Tim

**Comment by Quicksaver** [comment]
Actually the scrolling does work, just not the very first one (you have to scroll further). But I did just upload beta version 1.5.1b3 which should make it always work. You can find it at https://addons.mozilla.org/firefox/addon/omnisidebar/versions/. Care to give it a try? :)

**Comment by spideymouse** [comment]
Hi!

I did try it, but unfortunately I'm having the same result. I should
probably tell you that it stops working when I *undock *the sidebar from
the browser window. It does work when it's docked. Do you see the same
thing happening with your version?

**Comment by Quicksaver** [comment]
I did make a little mistake that caused the mouse wheel not to cycle through the tabs correctly. But it did cycle! I just uploaded beta version 1.5.1b4 that fixes that little mistake. Does it make any difference for you? If you disable your other add-ons and themes except for OSB and MileWideBack/EdgeWise, does it work with the sidebar undocked?

**Comment by spideymouse** [comment]
Hmm! I just installed the add-ons on a fresh new profile, and I still see
the issue with Edgewise. MileWideBack seems to work well now.

I think I have more details that might describe the nature of the bug: I
have OSB configured as undocked, *not* auto-hiding, in maximized mode. When
using a keyboard command like Ctrl+B or Ctrl+H or even the OSB Toolbar
Button to open the sidebar, EdgeWise breaks unless I mouseover the 1px line
above or below the floating sidebar. Can you try those settings and actions
and see if EdgeWise breaks for you too?

**Comment by Quicksaver** [comment]
That's just weird, I just tried those very same steps in a new profile and EdgeWise is working fine for me (haven't tried MileWideBack again since you said it works).

Can you clarify something for me please, is that line over or below the sidebar? As in, when you move the mouse to the edge, does the margin switch (blue glow) appear as in the screenshot, over the whole sidebar?
![osb_ew](https://cloud.githubusercontent.com/assets/802086/6070734/0cf80e86-ad87-11e4-95e7-470f334a787f.jpg)
For instance, can you still click it or shift click it? Or only in the small empty space just above or below the sidebar?

**Comment by spideymouse** [comment]
Hi Luis,

I once again created a new profile and tried it out again. Same results,
and I actually. I should have told you that I also unchecked the option for
"Click on the browser margin to open or close" (see picture below). As an
MWB/EW user, I do not want that blue margin to appear, plus the function
itself is not compatible with either of those add-ons anyway. So yes, once
I do check it, it does work on both add-ons (except of course the function
of "Click on the browser margin to open or close" will not work). I can
tweak OSB myself to get rid of the blue margin, but in general you might
want to guard against MWB/EW users trying to uncheck that option or
something. Thanks for the hint!

[image: Inline image 2]

**Comment by Quicksaver** [comment]
Actually, you can still use OSB's clickable margin with MWB/EW, except that to toggle the sidebar you have to click it while holding down the shift key, as to not interfere with MWB/EW's actions ([it's in the description ;)](https://addons.mozilla.org/firefox/addon/omnisidebar/) ).

Anyway, I was sure I had tried that combination of settings, but you're right of course, it's not working if the clickable margin is disabled. I already fixed it and uploaded beta version 1.5.1b5 if you want to try it. I think this will be the one. :)
