### ISSUE TITLE
Why this white space - 1.5.2

### ISSUE THREAD

**Issue by nonentity1001** [Quicksaver/OmniSidebar#76]
Large white space area at top of add ons side bar, was not there in 1.5.1

See  ![capture](https://cloud.githubusercontent.com/assets/10053529/6243909/a1b6b726-b79f-11e4-81a7-800db4fe81b0.JPG)

tks

**Comment by Quicksaver** [comment]
The light borders around should be easy to fix, but that large space I must admit I have no idea where it's coming from... I need to investigate.

**Comment by nonentity1001** [comment]
I use the FT Deep Dark theme, I don't see the big white square with the Default theme

**Comment by Quicksaver** [comment]
This should be fixed in the next version of FT DeepDark. Let me know if, when you update, you still see the issue.

**Comment by nonentity1001** [comment]
Hi - installed latest beta - fixed thanks a lot.

I'm wondering if it might be possible to fix a similar issue with Feed Sidebar - for some reason this irritates me less (or differently) to the other one hence I never reported it

![capture](https://cloud.githubusercontent.com/assets/10053529/6591499/27ae6ab0-c815-11e4-8bd3-199d492aa525.JPG)

**Comment by Quicksaver** [comment]
You really should ask FT DeepDark's developer. I'm sure it'll be easy to fix. :)

**Comment by nonentity1001** [comment]
IIRC I did that a long time ago - maybe I'll ask again.  Its often hard to "guess" what causes a misbehave - the core, a theme, an extension, or even a plugin.  With the Add-On sidebar problem it was obvious - as it manifested right after I did the Omnibar update.

Cheers
