### ISSUE TITLE
Undocked sidebar jumps.

### ISSUE THREAD

**Issue by streetwolf** [Quicksaver/OmniSidebar#77]
Version 1.5.3.

1. Display undocked sidebar by moving cursor to the left hand side of the screen.  This is where I place my sidebar.  A maximized window should be used to make the problem easier to see although a normal window has the same problem.

2. Move the pointer to the right while staying over the sidebar.

3. Move the pointer to the far left and notice the right side of the sidebar moves in and out a little bit.

**Comment by Quicksaver** [comment]
I don't see this, are you using any sort of theme?

**Comment by streetwolf** [comment]
I’m testing with a new profile and found something else strange.  I normally have the pref extensions.omnisidebar.aboveSquared set to true.  On my test profile I took the default which is false.  When my undocked/auto open/close sidebar is opened or closed the icons appear first then a second later comes the text.  This does NOT happen when the pref is set to true.  Works this way with e10s and non-e10s.

 

So far I can’t reproduce my original problem.  Could be another OSB pref or an add-on.  I’ll keep investigating.

**Comment by Quicksaver** [comment]
> I normally have the pref extensions.omnisidebar.aboveSquared set to true. On my test profile I took the default which is false. When my undocked/auto open/close sidebar is opened or closed the icons appear first then a second later comes the text. This does NOT happen when the pref is set to true.

I'm pretty sure this is the same as in #67, but the detail about aboveSquared is very interesting! In particular, it's the border radius that's causing the whole thing it seems! See my latest comment in ([bug 1090554](https://bugzilla.mozilla.org/show_bug.cgi?id=1090554)) if you'd like for more info.

I'll take a look at the prefs you've sent me by e-mail and see if I can reproduce the bug you initially described

**Comment by streetwolf** [comment]
Some more info on the ‘jumpy’ sidebar.  When I disable transition effects and move my pointer back to the left side the whole sidebar disappears for a split second then reappears.

**Comment by streetwolf** [comment]
I’ve attached a video of the problem with transition effects disabled.

**Comment by Quicksaver** [comment]
Attachments don't work through e-mail to github, you'll have to e-mail it to me directly.

**Comment by Quicksaver** [comment]
You were right in your last e-mail, it was definitely the delays. I just uploaded 1.5.4b1 with a fix for this. Care to try it out? https://addons.mozilla.org/firefox/addon/omnisidebar/versions/

**Comment by streetwolf** [comment]
All fixed.  Leave it to me to find something like this.

 

Btw.. the icons appearing before the text seems to have gone away.  Could be because I run the inbounds which might have introduced the problem and then fixed it or backed off.

**Comment by Quicksaver** [comment]
It's possible. I was told a related bug was fixed yesterday that could also fix that, I was just waiting for it to hit today's Nightly to test it. Guess that's a good sign it's fixed for you. :)
