### ISSUE TITLE
Simplify some menu names

### ISSUE THREAD

**Issue by sergwish** [Quicksaver/OmniSidebar#79]
"Add-ons Sidebar" could be named simply "Add-ons"
"View Page Info" could be named simply "Page Info"

**Comment by Quicksaver** [comment]
True. :)

**Comment by Keith94** [comment]
But if you have the Add-ons Sidebar button sharing the same label and icon as the default Add-ons button, won't it become harder to distinguish between the two inside the menu button or customize mode?

The same can be said for the Downloads Sidebar button and the default Downloads button; in customize mode I can't identify which is which. It doesn't help that they have identical wording in their tooltips either.
