### ISSUE TITLE
add-on sidebar display issue for Preferences Monitor ext.

### ISSUE THREAD

**Issue by atomGit** [Quicksaver/OmniSidebar#82]
the Preferences Monitor ext. does not display well in the add-on sidebar and you can't change the settings which are displayed in combination controls
https://addons.mozilla.org/en-US/firefox/addon/preferences-monitor/

ff 36.0.1
OS 1.5.4

**Comment by Quicksaver** [comment]
Thanks for letting me know! This will be fixed in the next version, I hope to upload it in about a week, so it will still take a little while, I hope it doesn't bother you much in the meantime.
