### ISSUE TITLE
add-on sidebar display issue for Shim Storage ext.

### ISSUE THREAD

**Issue by atomGit** [Quicksaver/OmniSidebar#83]
seems like the add-on panel display is going to cause problems with several add-ons
win 7
osb 1.5.4
ff 36.0.1
Shim Storage input control is not displayed correctly - it's too small
https://addons.mozilla.org/en-US/firefox/addon/shim-storage/

**Comment by Quicksaver** [comment]
This should be fixed by 06a6f7d583fec18c8353dde556f24f6b02b7c6fc as well.
