### ISSUE TITLE
New window glitch

### ISSUE THREAD

**Issue by sergwish** [Quicksaver/OmniSidebar#84]
When I open new (2nd, 3rd, etc.) firefox window, the sidebar in it initially behaves differently from the sidebar in other windows:
* main toolbar button is always up (needs **two** clicks to get it down), even if it was down in existing window;
* sidebar toolbar is not present, even if it was turned on in configuration.

After switching off-then-on the sidebar toolbar option in configuration:
* buttons on sidebar toolbar are gray, even if it was set to colorful;
* sidebar title and close button are shown, even if they were turned off.

**Comment by Quicksaver** [comment]
There's probably some kind of initialization issue going on in the extra windows, that's preventing the sidebar from working properly.. Thanks for letting me know, I'll be sure to take a look into it and let you know.

**Comment by Quicksaver** [comment]
Could you please check out beta version 1.6b4 (https://github.com/Quicksaver/OmniSidebar/releases/tag/v1.6b4) and see if these issues still happen with it? I can't reproduce any of them with that beta.

**Comment by Quicksaver** [comment]
Correction, please try v1.6b5 https://github.com/Quicksaver/OmniSidebar/releases/tag/v1.6b5

**Comment by Quicksaver** [comment]
Since I haven't heard back, I'm closing this issue. Feel free to re-open if you still have problems.
