### ISSUE TITLE
I can not install in firefox 31.6.0esr

### ISSUE THREAD

**Issue by zvitalikus** [Quicksaver/OmniSidebar#85]
Extension not install in firefox 31.6.0esr. 
Possible that anything to do with it?

**Comment by zvitalikus** [comment]
Version 1.4.7 work, ok

**Comment by Quicksaver** [comment]
Unfortunately I can't keep supporting older versions of firefox, even within the ESR the changes between 31 and the current version are too great to be manageable. Until ESR updates to a more recent base version of firefox, I'm afraid you'll have to use an older version of the add-on like 1.4.7 yeah.

**Comment by zvitalikus** [comment]
31.6 new version 26-Mar-2015. Interface by 36-37.
