### ISSUE TITLE
[feature req] open panels in external UI

### ISSUE THREAD

**Issue by atomGit** [Quicksaver/OmniSidebar#87]
would be great to be able to open some panels, such as the console, in their native, external UI sometimes 

if this could be done by a middle-click on the icon, that would be fantastic

**Comment by Quicksaver** [comment]
That goes beyond the point of the add-on; remember this is a "Sidebar"-oriented add-on. ;)

Having said that, there are a few ways you can do this already, for instance [Toolbar Buttons](https://addons.mozilla.org/firefox/addon/toolbar-buttons/) includes a button for the console that should open it in its native UI. You also have the original keyboard shortcuts (Ctrl+Shift+J for the console) which, as long as you don't enable the corresponding "Always open in the sidebar..." option, should take you to the original UI as well.
