### ISSUE TITLE
omniside bar latest version incompatible with Firefox 33.0.3?

### ISSUE THREAD

**Issue by qws25** [Quicksaver/OmniSidebar#88]
the problems is omnisidebar 1.5->1.5.4 onl compatible with firefox Works with Firefox 34.0 and later

And Version 1.4.7 is too old  with Firefox 8.0 and later it works strange

**Comment by Quicksaver** [comment]
Yes it is, there have been too many changes in firefox in the meantime for me to be able to keep backwards compatibility like that.

**Comment by qws25** [comment]
I open xpi using winrar and edit install.rdf 
<em:minVersion>33.0</em:minVersion> like this and it work fine :P
thank anyway :P
