### ISSUE TITLE
Sidebar close button bug

### ISSUE THREAD

**Issue by assertnotnull** [Quicksaver/OmniSidebar#90]
When closing the sidebar with it's close icon, the menu icon stays active.

It also causes the sidebar to appear on the next start of the browser.

**Comment by Quicksaver** [comment]
#89

**Comment by brianvanderburg2** [comment]
I can verify this seems to have fixed it.  I also noticed before installing the pre-release that a work-around was to close the sidebar with the hot-key combination.  Then it would stay closed when restarted or opening a new window.
