### ISSUE TITLE
Show/hide sidebar on mouse button _press_ option

### ISSUE THREAD

**Issue by m0n** [Quicksaver/OmniSidebar#91]
Very important (for me :wink:) and easy-to-implement enhancement: sub-option "On button press" checkbox for "Click on the browser margin to open or close".

Real-world example: I using "Click on the browser margin to open or close" feature, and I open sidebar just temporaly and frequently (means I using "Close/Hide the sidebar when it loses focus"). Because I developing for web, I using mouse really quickly. Now I slow-motion the situation: I snap/throw pointer to the side of the window, and at the end of the traction pointer is trying to push the edge of the monitor (browser always maximized) FOR SURE. At this point I press mouse button. Time is c.a. T0+50ms. Now I move pointer to the opposite direction to reach something on the sidebar, but I didn't released button yet. After c.a. 40ms I release button, and here is the problem: I'm already moved off sidebar-activator area, so sidebar will not show up :cry:

This whole process is a reflex of mine, happening during a blink of an eye.

Yes, I could use "Automatically hide to the side" with 0ms delays but unfortunatelly I _must_ to use right-side sidebar and this way very easy to open sidebar when I just like to scroll with the scrollbar...

I did hacked mainSidebar.xul:

```javascript
    <hbox id="browser">
      //bullsitz here
      //   onclick="objName.clickSwitcher(event, objName.mainSidebar);"
           onmousedown="objName.clickSwitcher(event, objName.mainSidebar);"
      //bullsitz here
    </hbox>
```
I'm absolutelly do not know what I done, but works very well :smiley:. Untested, but seems solves my problem until here will be an official checkbox for this.

Or, if this change is OK then please update official code!

Many thanx for this űber-fasza extension!

**Comment by Quicksaver** [comment]
I agree completely, I should have done it on mouse down from the start. The next version will do this.
