### ISSUE TITLE
Omnisidebar Always Open At Startup.

### ISSUE THREAD

**Issue by MasterLive013** [Quicksaver/OmniSidebar#94]
Probably has an easy solution which me the fool can't find but every time I start Firefox (or a new window) the Omnisidebar always open at the side. I would for this to not happen. How would I fix this?

(When I disable the Omnisidebar the problem goes away.)

Thanks!

**Comment by Quicksaver** [comment]
You're not a fool. ;)

That's a bug in the current version, which I've already fixed in version 1.6. Please give it a try and let me know if you still have issues, you can find it at the top of https://addons.mozilla.org/firefox/addon/omnisidebar/versions/
