### ISSUE TITLE
Auto Hide doesn't work

### ISSUE THREAD

**Issue by mbecoool** [Quicksaver/OmniSidebar#95]
http://savepic.net/6996655.png
http://savepic.net/6997679.png
With these settings, If open the bookmark with middle click, sidebar not hide when it loses focus.

**Comment by Quicksaver** [comment]
Please try the latest version 1.6 (at the top of https://addons.mozilla.org/firefox/addon/omnisidebar/versions/) and let me know if that still happens.

**Comment by mbecoool** [comment]
Nothing changed, sidebar not hide when it loses focus.

**Comment by Quicksaver** [comment]
You're right. Could you try beta version 1.6.1b2 (https://github.com/Quicksaver/OmniSidebar/releases/tag/v1.6.1b2) and let me know how it works for you please?

**Comment by mbecoool** [comment]
Now it works, thank you!
