### ISSUE TITLE
why is foxfire continually freezing.

### ISSUE THREAD

**Issue by smasaoka** [Quicksaver/OmniSidebar#99]

**Comment by Quicksaver** [comment]
I don't know. Does it not freeze if you disable OmniSidebar?

**Comment by smasaoka** [comment]
I'm new at this. When it does freeze, I then get the omniSidebar in a new
tab.
It is frustrating!

On Sat, Aug 22, 2015 at 4:03 PM, Luís Miguel <notifications@github.com>
wrote:

> I don't know. Does it not freeze if you disable OmniSidebar?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Quicksaver/OmniSidebar/issues/99#issuecomment-133750030>
> .
>



-- 
Shirley Masaoka
www.shirleyswritings.com

**Comment by Quicksaver** [comment]
What do you get in a new tab? Have you tried disabling all your add-ons except for OmniSidebar and see how firefox behaves then?

**Comment by smasaoka** [comment]
Thank you for your fast reply.

I just went from 8 to 10. Noticed when I open a new tab there were a
zillion pages I had been before, and I removed them. Would this help?  I
will try to do also what you said.

Thanks again.

On Sat, Aug 22, 2015 at 6:34 PM, Luís Miguel <notifications@github.com>
wrote:

> What do you get in a new tab? Have you tried disabling all your add-ons
> except for OmniSidebar and see how firefox behaves then?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Quicksaver/OmniSidebar/issues/99#issuecomment-133760264>
> .
>



-- 
Shirley Masaoka
www.shirleyswritings.com

**Comment by Quicksaver** [comment]
> I just went from 8 to 10. Noticed when I open a new tab there were a zillion pages I had been before, and I removed them. Would this help?

I really don't know what any of that means...

**Comment by Quicksaver** [comment]
I'll need more information about this in order for me to do anything. Please re-open if you can provide more information or if you can better explain what issue you are having, as I said I really didn't understand.

**Comment by smasaoka** [comment]
It's OK started happening when using windows 10 UGH. Now on Chrome and no
problems.

On Thu, Sep 10, 2015 at 5:17 AM, Luís Miguel <notifications@github.com>
wrote:

> I'll need more information about this in order for me to do anything.
> Please re-open if you can provide more information or if you can better
> explain what issue you are having, as I said I really didn't understand.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Quicksaver/OmniSidebar/issues/99#issuecomment-139178790>
> .
>



-- 
Shirley Masaoka
www.shirleyswritings.com
